# @Author: vxhly
# @Date:   2018-03-14 05:05:51 pm
# @Email:  pengchengou@gmail.com
# @Filename: .travis.yml
# @Last modified by:   vxhly
# @Last modified time: 2018-03-14 05:09:57 pm
# @License: MIT

language: node_js
node_js: '9'
dist: trusty
before_install:
  - npm i -g gulp
install:
  - npm install
deploy:
  provider: npm
  skip_cleanup: true
  email: pengchengou@gmail.com
  api_key:
    secure: esLh60RWpryoFj3FZcFPvcxZhf4DlzFVgdExm+ZMPz5GejZ3i1InP5H4Zi/JgS9gl0b1NocH6EVrpkq1mPFkRGHJhedzgkKcV87TLxbmc9Vu0rxkqZAGA7yCoAsW03/WLLD3nsfI6KmnUNgLS6dV8R3ji90M0bByuxOMs/2kGb8J5PgxyC20tqNPcWssP1XWCJse+goFUYpwI+Wzi1IJDr56aYLxTLEulUpbWIf/A68Yh5G5+9aeqObqJOuURi0Xt/XPv59q6gb71zpqmLzs/ArYBeMqjVlg8NO4EJ4zH8KHCwCAmNV7htvaiiUaTiE2lr6MD1LU+RJeRFEi66TlgpgLYIgdwCXUVKoDIgXVUBkzQHQmmxI9qYJ0UKZ0owhypE2DYcsH66DXT+nxBn9i/1Qby8EQtEofu6kh9dDBtwHFigyZGOP09cuIqndpJKy8zqL8EV7qu7pkwrjQQb6s5XCdpe05bQKinxfT4oBdFUIfFd3S+4aDaYbXTXT02hlO7DaTGCZUfreAcY+7sVeE18Ph0X3R8UUtGUBqADshCsCA2GM5q63WheBNYkhn5/hfm1pxEYMBf1IPvH0hJBtmP/5l+4loTab42FwfBlt5ZBLoNLfEedHbIG3CKQv51Ik4H93WqpiRaP5FDi+IdxQRgia/EyZm54AL9ZXMk7KYG7Y=
  on:
    tags: true
    repo: vxhly/grid-scss
